# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setMinimumSize(QtCore.QSize(480, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        MainWindow.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 177, 255, 255), stop:1 rgba(0, 20, 37, 255));\n"
"border-radius: 8px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(130, 0))
        self.frame.setMaximumSize(QtCore.QSize(130, 16777215))
        self.frame.setStyleSheet("background-color: rgba(255, 255,255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("image: url(:/image/image_icon/STM32MCU.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(326, 216))
        self.frame_2.setMaximumSize(QtCore.QSize(326, 216))
        self.frame_2.setStyleSheet("\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 8, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Btn_Device_Full_Name = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Btn_Device_Full_Name.setFont(font)
        self.Btn_Device_Full_Name.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/image_icon/cpu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Device_Full_Name.setIcon(icon)
        self.Btn_Device_Full_Name.setIconSize(QtCore.QSize(35, 35))
        self.Btn_Device_Full_Name.setObjectName("Btn_Device_Full_Name")
        self.verticalLayout.addWidget(self.Btn_Device_Full_Name)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("border: none;\n"
"border-radius: 1px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMinimumSize(QtCore.QSize(95, 0))
        self.label_3.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.Btn_Device_Series = QtWidgets.QPushButton(self.frame_5)
        self.Btn_Device_Series.setMinimumSize(QtCore.QSize(200, 30))
        self.Btn_Device_Series.setMaximumSize(QtCore.QSize(250, 30))
        self.Btn_Device_Series.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 100, 255, 50);\n"
"border-radius: 4px;")
        self.Btn_Device_Series.setObjectName("Btn_Device_Series")
        self.gridLayout_2.addWidget(self.Btn_Device_Series, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setMinimumSize(QtCore.QSize(95, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.Btn_Project_Bgr = QtWidgets.QPushButton(self.frame_5)
        self.Btn_Project_Bgr.setMinimumSize(QtCore.QSize(200, 30))
        self.Btn_Project_Bgr.setMaximumSize(QtCore.QSize(250, 30))
        self.Btn_Project_Bgr.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 100, 255, 50);\n"
"border-radius: 4px;")
        self.Btn_Project_Bgr.setObjectName("Btn_Project_Bgr")
        self.gridLayout_2.addWidget(self.Btn_Project_Bgr, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.Box_Optimize = QtWidgets.QComboBox(self.frame_5)
        self.Box_Optimize.setMinimumSize(QtCore.QSize(200, 30))
        self.Box_Optimize.setMaximumSize(QtCore.QSize(250, 30))
        self.Box_Optimize.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 100, 255, 50);\n"
"border-radius: 4px;")
        self.Box_Optimize.setObjectName("Box_Optimize")
        self.Box_Optimize.addItem("")
        self.Box_Optimize.addItem("")
        self.Box_Optimize.addItem("")
        self.Box_Optimize.addItem("")
        self.Box_Optimize.addItem("")
        self.Box_Optimize.addItem("")
        self.Box_Optimize.addItem("")
        self.gridLayout_2.addWidget(self.Box_Optimize, 2, 1, 1, 1)
        self.CB_Printf_Float = QtWidgets.QCheckBox(self.frame_5)
        self.CB_Printf_Float.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 100, 255, 80);\n"
"border-radius: 4px;\n"
"padding-left: 8px;")
        self.CB_Printf_Float.setChecked(True)
        self.CB_Printf_Float.setObjectName("CB_Printf_Float")
        self.gridLayout_2.addWidget(self.CB_Printf_Float, 3, 0, 1, 2)
        self.CB_Scanf_Float = QtWidgets.QCheckBox(self.frame_5)
        self.CB_Scanf_Float.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 100, 255, 80);\n"
"border-radius: 4px;\n"
"padding-left: 8px;")
        self.CB_Scanf_Float.setObjectName("CB_Scanf_Float")
        self.gridLayout_2.addWidget(self.CB_Scanf_Float, 4, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame_5)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 36))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 36))
        self.frame_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LE_Project_Dir = QtWidgets.QLineEdit(self.frame_4)
        self.LE_Project_Dir.setMinimumSize(QtCore.QSize(0, 35))
        self.LE_Project_Dir.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 100, 255, 80);\n"
"border: 2px solid rgb(0, 150, 255);")
        self.LE_Project_Dir.setObjectName("LE_Project_Dir")
        self.horizontalLayout_2.addWidget(self.LE_Project_Dir)
        self.Btn_Browser = QtWidgets.QPushButton(self.frame_4)
        self.Btn_Browser.setMinimumSize(QtCore.QSize(90, 35))
        self.Btn_Browser.setStyleSheet("QPushButton#Btn_Browser{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 150, 255);\n"
"}\n"
"QPushButton#Btn_Browser::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 100, 200);\n"
"}\n"
"QPushButton#Btn_Browser::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 150, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/image_icon/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Browser.setIcon(icon1)
        self.Btn_Browser.setIconSize(QtCore.QSize(25, 25))
        self.Btn_Browser.setObjectName("Btn_Browser")
        self.horizontalLayout_2.addWidget(self.Btn_Browser)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 36))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 36))
        self.frame_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Btn_Quit = QtWidgets.QPushButton(self.frame_3)
        self.Btn_Quit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Quit.setFont(font)
        self.Btn_Quit.setStyleSheet("QPushButton#Btn_Quit{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(224, 27, 36);\n"
"}\n"
"QPushButton#Btn_Quit::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(180, 0, 0);\n"
"}\n"
"QPushButton#Btn_Quit::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 50, 255);\n"
"}")
        self.Btn_Quit.setObjectName("Btn_Quit")
        self.horizontalLayout.addWidget(self.Btn_Quit)
        self.Btn_Restore = QtWidgets.QPushButton(self.frame_3)
        self.Btn_Restore.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Restore.setFont(font)
        self.Btn_Restore.setStyleSheet("QPushButton#Btn_Restore{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(245, 194, 17);\n"
"}\n"
"QPushButton#Btn_Restore::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(200, 150, 17);\n"
"}\n"
"QPushButton#Btn_Restore::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 50, 255);\n"
"}")
        self.Btn_Restore.setObjectName("Btn_Restore")
        self.horizontalLayout.addWidget(self.Btn_Restore)
        self.Btn_Setup = QtWidgets.QPushButton(self.frame_3)
        self.Btn_Setup.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Setup.setFont(font)
        self.Btn_Setup.setStyleSheet("QPushButton#Btn_Setup{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 220, 0);\n"
"}\n"
"QPushButton#Btn_Setup::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 150, 0);\n"
"}\n"
"QPushButton#Btn_Setup::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 50, 255);\n"
"}")
        self.Btn_Setup.setObjectName("Btn_Setup")
        self.horizontalLayout.addWidget(self.Btn_Setup)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STM-EDF setup tool"))
        self.Btn_Device_Full_Name.setText(_translate("MainWindow", "STM32xxxxxxxxx"))
        self.label_3.setText(_translate("MainWindow", "Device series"))
        self.Btn_Device_Series.setText(_translate("MainWindow", "Unknown "))
        self.label_4.setText(_translate("MainWindow", "Background"))
        self.Btn_Project_Bgr.setText(_translate("MainWindow", "None"))
        self.label_2.setText(_translate("MainWindow", "Optimize level"))
        self.Box_Optimize.setItemText(0, _translate("MainWindow", "None(o0)"))
        self.Box_Optimize.setItemText(1, _translate("MainWindow", "Optimize for debug(og)"))
        self.Box_Optimize.setItemText(2, _translate("MainWindow", "Optimize for size(os)"))
        self.Box_Optimize.setItemText(3, _translate("MainWindow", "Optimize for speed(ofast)"))
        self.Box_Optimize.setItemText(4, _translate("MainWindow", "Optimize(o1)"))
        self.Box_Optimize.setItemText(5, _translate("MainWindow", "Optimize for more(o2)"))
        self.Box_Optimize.setItemText(6, _translate("MainWindow", "Optimize for most(o3)"))
        self.CB_Printf_Float.setText(_translate("MainWindow", "Option printf float"))
        self.CB_Scanf_Float.setText(_translate("MainWindow", "Option scanf float"))
        self.LE_Project_Dir.setPlaceholderText(_translate("MainWindow", "Project directory....."))
        self.Btn_Browser.setText(_translate("MainWindow", "Browser"))
        self.Btn_Quit.setText(_translate("MainWindow", "Quit"))
        self.Btn_Restore.setText(_translate("MainWindow", "Restore"))
        self.Btn_Setup.setText(_translate("MainWindow", "SetUp"))
import guiimg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
